services:
  sonarr-anime:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr-anime
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./anime:/config
      - /media/david/Larry/Anime:/tv
      - /media/downloads:/media/downloads
    ports:
      - 9090:8989
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - anime

  bazaar-anime:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr-anime
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./bazaar:/config
      - /media/david/Larry/Anime:/tv
    ports:
      - 6767:6767
    restart: unless-stopped
    networks:
      - anime

networks:
  anime:
    driver: bridge

