version: "3"

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    user: portainer
    ports:
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer:/data
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    user: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
