services:
  sonarr-tv:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr-tv
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./sonarr:/config
      - /media/david/Larry/TV:/tv
      - /media/downloads:/media/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
        - tv

networks:
  tv:
    driver: bridge
