services:
  prowlarr-indexer:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr-indexer
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - indexer

networks:
  indexer:
    driver: bridge
